/**
 * PlantLog v4 — CONFIG MODULE
 * Translations, constants
 * Lines 1–87 of original monolithic file
 */


// ═══════ TRANSLATIONS ═══════
const T={
  en:{
    home:'Home',trips:'Trips',tasks:'Tasks',leave:'Leave',settings:'Settings',
    tripsMonth:'Trips',pendingTasks:'Tasks today',leaveDays:'Leave days',
    upcomingTrips:'Upcoming trips',recentReports:'Recent reports',todayTasks:"Today's tasks",
    noTrips:'No upcoming trips. Tap + to create.',noReports:'No completed reports yet.',noTasks:'No tasks yet. Tap + to add.',
    myTrips:'My Trips',all:'All',planned:'Planned',inProgress:'In Progress',completed:'Completed',
    pending:'Pending',done:'Done',kanban:'Kanban',
    delete:'Delete',openReport:'Open Report',
    tab1:'1 Checklist',tab2:'2 Readings',tab3:'3 Issues',tab4:'4 Team',tab5:'5 Tasks',tab6:'6 Sign-off',
    inspectionChecklist:'INSPECTION CHECKLIST',addCheckItem:'Add item',nextReadings:'Next: Readings →',
    equipmentReadings:'EQUIPMENT READINGS',addReading:'Add reading',nextIssues:'Next: Issues →',
    noIssues:'No issues found.',addIssue:'Add issue',nextTeam:'Next: Team →',
    teamSignoffs:'TEAM & SIGN-OFFS',addTeamMember:'Add member',nextSignoff:'Next: Sign-off →',
    workSummary:'Work summary',result:'Result',remarks:'Remarks',
    engineerSig:'Signature',signHint:'Sign above with finger or stylus',clearSig:'Clear',
    exportPdf:'Export PDF',exportPdfReport:'Export Report',downloadPdf:'Download PDF',
    emailPdf:'Email Report',markCompleted:'Mark completed',
    leavePlanner:'Leave Planner',workTrip:'Work trip',holiday:'Holiday',tripDays:'Trip days',clearDay:'Clear day',
    addTaskForDay:'Add task for this day',
    fullName:'Full name',jobTitle:'Job title',company:'Company',employeeId:'Employee ID',
    defaultTeam:'Default Team',industryTemplates:'Industry templates',
    loadChecklistTemplates:'Load checklist for your industry',checklistTemplates:'Checklist templates',
    manageDefaultItems:'Manage default items',clearData:'Clear all data',
    notifications:'Notifications',enableNotif:'Enable notifications',notifDesc:'Get reminders for trips, tasks & leave',
    newTrip:'New Trip',plantName:'Plant name *',location:'Location',visitDate:'Date *',endDate:'End date',
    purposeScope:'Purpose',contactPerson:'Contact',transport:'Transport',saveTrip:'Save trip',cancel:'Cancel',
    newTask:'New Task',taskTitle:'Task title *',description:'Description',dueDate:'Due date *',time:'Time',
    priority:'Priority',linkedTrip:'Linked trip',saveTask:'Save task',
    itemName:'Item name *',notesOptional:'Notes',addItem:'Add',
    equipmentName:'Equipment *',value:'Value *',unit:'Unit',status:'Status',inSpec:'In spec',outOfRange:'Out of range',notes:'Notes',
    issueTitle:'Title *',details:'Details',severity:'Severity',recommendedAction:'Action',photoEvidence:'Photos',addPhoto:'Add photo',
    name:'Name *',rolePosition:'Role',organization:'Organization',signoffRequired:'Sign-off?',addMember:'Add',
    selectIndustry:'Select your industry:',
    emailReport:'Email Report',recipientEmail:'To *',ccEmail:'CC',subject:'Subject',message:'Message',send:'Send',
    done2:'Done',add:'Add',partial:'Partial',deferred:'Deferred',
    goodMorning:'Good morning',goodAfternoon:'Good afternoon',goodEvening:'Good evening',
    installApp:'Install PlantLog on your phone for offline use',install:'Install',
    taskOverdue:'Overdue',taskDueToday:'Due today',taskUpcoming:'Upcoming',
    noIssuesFound:'No issues.',noReadings:'No readings.',
    inProgress2:'In Progress'
  },
  vi:{
    home:'Trang chủ',trips:'Chuyến đi',tasks:'Nhiệm vụ',leave:'Nghỉ phép',settings:'Cài đặt',
    tripsMonth:'Chuyến đi',pendingTasks:'Việc hôm nay',leaveDays:'Ngày nghỉ',
    upcomingTrips:'Chuyến sắp tới',recentReports:'Báo cáo gần đây',todayTasks:'Nhiệm vụ hôm nay',
    noTrips:'Chưa có chuyến đi. Nhấn + để tạo.',noReports:'Chưa có báo cáo hoàn thành.',noTasks:'Chưa có nhiệm vụ. Nhấn + để thêm.',
    myTrips:'Chuyến của tôi',all:'Tất cả',planned:'Đã lên kế hoạch',inProgress:'Đang thực hiện',completed:'Hoàn thành',
    pending:'Chờ xử lý',done:'Xong',kanban:'Kanban',
    delete:'Xóa',openReport:'Mở báo cáo',
    tab1:'1 Danh mục',tab2:'2 Đo lường',tab3:'3 Sự cố',tab4:'4 Nhóm',tab5:'5 Nhiệm vụ',tab6:'6 Ký duyệt',
    inspectionChecklist:'DANH MỤC KIỂM TRA',addCheckItem:'Thêm mục',nextReadings:'Tiếp: Đo lường →',
    equipmentReadings:'SỐ LIỆU THIẾT BỊ',addReading:'Thêm số liệu',nextIssues:'Tiếp: Sự cố →',
    noIssues:'Không có sự cố.',addIssue:'Thêm sự cố',nextTeam:'Tiếp: Nhóm →',
    teamSignoffs:'NHÓM & KÝ DUYỆT',addTeamMember:'Thêm thành viên',nextSignoff:'Tiếp: Ký duyệt →',
    workSummary:'Tóm tắt công việc',result:'Kết quả',remarks:'Ghi chú',
    engineerSig:'Chữ ký',signHint:'Ký bằng ngón tay hoặc bút cảm ứng',clearSig:'Xóa',
    exportPdf:'Xuất PDF',exportPdfReport:'Xuất báo cáo',downloadPdf:'Tải PDF',
    emailPdf:'Gửi qua email',markCompleted:'Đánh dấu hoàn thành',
    leavePlanner:'Kế hoạch nghỉ phép',workTrip:'Công tác',holiday:'Ngày lễ',tripDays:'Ngày công tác',clearDay:'Xóa ngày',
    addTaskForDay:'Thêm nhiệm vụ cho ngày này',
    fullName:'Họ và tên',jobTitle:'Chức danh',company:'Công ty',employeeId:'Mã nhân viên',
    defaultTeam:'Nhóm mặc định',industryTemplates:'Mẫu theo ngành',
    loadChecklistTemplates:'Tải mẫu kiểm tra theo ngành',checklistTemplates:'Mẫu danh mục',
    manageDefaultItems:'Quản lý mẫu mặc định',clearData:'Xóa tất cả dữ liệu',
    notifications:'Thông báo',enableNotif:'Bật thông báo',notifDesc:'Nhắc nhở chuyến đi, nhiệm vụ & nghỉ phép',
    newTrip:'Chuyến mới',plantName:'Tên nhà máy *',location:'Địa điểm',visitDate:'Ngày thăm *',endDate:'Ngày kết thúc',
    purposeScope:'Mục đích',contactPerson:'Người liên hệ',transport:'Phương tiện',saveTrip:'Lưu chuyến',cancel:'Hủy',
    newTask:'Nhiệm vụ mới',taskTitle:'Tiêu đề *',description:'Mô tả',dueDate:'Ngày hạn *',time:'Giờ',
    priority:'Độ ưu tiên',linkedTrip:'Chuyến liên kết',saveTask:'Lưu nhiệm vụ',
    itemName:'Tên mục *',notesOptional:'Ghi chú',addItem:'Thêm',
    equipmentName:'Thiết bị *',value:'Giá trị *',unit:'Đơn vị',status:'Trạng thái',inSpec:'Đạt chuẩn',outOfRange:'Ngoài phạm vi',notes:'Ghi chú',
    issueTitle:'Tiêu đề *',details:'Chi tiết',severity:'Mức độ',recommendedAction:'Biện pháp',photoEvidence:'Ảnh',addPhoto:'Thêm ảnh',
    name:'Tên *',rolePosition:'Chức vụ',organization:'Đơn vị',signoffRequired:'Cần ký?',addMember:'Thêm',
    selectIndustry:'Chọn ngành để tải mẫu:',
    emailReport:'Gửi báo cáo',recipientEmail:'Đến *',ccEmail:'CC',subject:'Tiêu đề',message:'Nội dung',send:'Gửi',
    done2:'Xong',add:'Thêm',partial:'Một phần',deferred:'Hoãn lại',
    goodMorning:'Chào buổi sáng',goodAfternoon:'Chào buổi chiều',goodEvening:'Chào buổi tối',
    installApp:'Cài PlantLog lên điện thoại để dùng offline',install:'Cài đặt',
    taskOverdue:'Quá hạn',taskDueToday:'Hôm nay',taskUpcoming:'Sắp đến',
    noIssuesFound:'Không có sự cố.',noReadings:'Chưa có số liệu.',
    inProgress2:'Đang thực hiện'
  }
};
